baseurl = "/"
languageCode = "en-uk"
title = "Mikko Marttila"
theme = "hugo-lithium-theme"
enableEmoji = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    pre = ""
    url = "/about/"
    weight = -1
[[menu.main]]
    name = " "
    identifier = "github"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/mikmart/"
    weight = 2
[[menu.main]]
    name = " "
    identifier = "linkedin"
    pre = "<i class='fab fa-linkedin fa-lg'></i>"
    url = "https://www.linkedin.com/in/mikmart/"
    weight = 3

[params]
    description = "Thoughts and notes on R, statistics, and programming."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "profile.jpg"
    width = 50
    height = 50
    alt = "Logo"
